### ISSUE TITLE
Setting meta tags

### ISSUE THREAD

**Issue by Ader0nke** [octfx/wiki-seo#12]
Hello, good evening

My team has been working on a wiki that we created https://wiki.lodgecompliance.com/Lodge_Compliance We downloaded and installed the wikiSEO extension version 2.5.0 and it seemed to be working fine. But for a few days now I have been trying to edit the title, meta descriptions and keywords but the changes are not reflecting on google SERP. 

Although I can see the title change from the tabs of my web browser, but when I search on google, I see that neither the title or description has changed.

Kindly assist with any tips on how to fix this.

Thank you

**Comment by octfx** [comment]
Hey there,

SERP results do not change instantly. It usually takes a few days to a week until the results refresh.  
In the meantime you can add your site to the [google search console](https://search.google.com/search-console/about) and manually request a refresh.

Cheers

**Comment by Ader0nke** [comment]
Thank you for your reply.
