### ISSUE TITLE
Support Naver Site Verification

### ISSUE THREAD

**Issue by revi** [octfx/wiki-seo#14]
Somewhat similar to Yandex, [Naver](https://enwp.org/Naver) has won the Search Engine battle in South Korea, and takes care of (approximately) 75% of search traffic in Korea.

It has following syntax for meta tag verification: `<meta name="naver-site-verification" content="$TAG" />` (Sorry, docs are only available in [Korean](https://help.naver.com/support/contents/contents.help?serviceNo=14882&categoryNo=14928))

Can you add it? Thanks!

**Comment by octfx** [comment]
Hey there! This is now implemented in 9135f12.
You can add the key by setting `$wgNaverSiteVerificationKey = 'KEY';`.
