### ISSUE TITLE
Auto description doesn't work on page save unless parser function is present

### ISSUE THREAD

**Issue by porplemontage** [octfx/wiki-seo#15]
If you set `$wgWikiSeoEnableAutoDescription=true` **without** setting `$wgWikiSeoSaveAutoDescriptionOnView` to true, the auto description is not set on page save unless the seo parser function/tag is on the page. I think the auto description should be added to pages without the tag, using a save page hook (?)

**Comment by octfx** [comment]
That was somewhat intentional, but I see your point, I'll think about it!
