### ISSUE TITLE
Auto descriptions don't update once generated

### ISSUE THREAD

**Issue by porplemontage** [octfx/wiki-seo#16]
If I change the opening content of the page, the auto description doesn't update. On page save, it should check if auto descriptions are enabled and update the description if so.

**Comment by octfx** [comment]
Thanks for the report, I'll check that out later.

**Comment by octfx** [comment]
Both issues should be fixed in the latest commit.

The setting `$wgWikiSeoSaveAutoDescriptionOnView`  was removed, as it now runs on page save

**Comment by porplemontage** [comment]
Awesome changes, thank you!

I just want to note one thing though. As I think you know, the new method of getting the description is always one revision behind, because on page save it pulls from the API (except for brand new pages) which could have a different opener than the actual text being saved. This is not a huge problem, but it's like the one thing that's a downgrade compared to Description2, and I wonder if we could have the best of both worlds.

The idea I had is this: on page save, set the description to null. Then on page view, set the description from the API if it is null. Or maybe instead of null, there could be a special value set on page save so that only pages with that value call the API next page view. Then brand new pages could also pull from the API instead of having a special case. I'm pretty much going against my initial suggestion now since I didn't think about the API being outdated on page save until I had the working code in front of me, so I apologize for that... What do you think?

**Comment by octfx** [comment]
I've noticed the api problem as well, for new pages I've mitigated that somewhat by using the first 160 chars of page content. 

I'll think about a solution for retrieving the newest description on save.

Maybe a textextracts "light" or some form there of, as we have access to the page content

**Comment by porplemontage** [comment]
I actually like that this uses TextExtracts because the functionality already exists and it works alongside `$wgExtractsRemoveClasses`, for example. Description2 does its own parsing and the regex gets messy, plus I had to hack in some of my own regex for certain cases, not as nice. That's why I gravitate to basically bringing back some of the `SaveAutoDescriptionOnView` functionality, but combined with a description purge on edit.

**Comment by octfx** [comment]
Ah shoot, I missed your PR

I've implemented the description generation through deferred updates.
The general execution flow is:
Edit occurs -> page is saved -> displayed to user -> description is generated

This means that the description is only visible after a page refresh, but will use the latest page data on every save.

Do you mind checking out the latest commit and test?

**Comment by porplemontage** [comment]
I just noticed mine had an issue with the page info, but looks like your version is working perfectly. I'm seeing the updated descriptions right after edit. The only issue I saw is this warning (if you visit page info before the null edit):

https://github.com/porplemontage/wiki-seo/commit/ede666ba562eab65e952ef67393cadf24cc264ee

**Comment by octfx** [comment]
I'll merge the null check as soon as the mediawiki checks pass

**Comment by alistair3149** [comment]
> I've noticed the api problem as well, for new pages I've mitigated that somewhat by using the first 160 chars of page content.
> 
> I'll think about a solution for retrieving the newest description on save.
> 
> Maybe a textextracts "light" or some form there of, as we have access to the page content



> I actually like that this uses TextExtracts because the functionality already exists and it works alongside `$wgExtractsRemoveClasses`, for example. Description2 does its own parsing and the regex gets messy, plus I had to hack in some of my own regex for certain cases, not as nice. That's why I gravitate to basically bringing back some of the `SaveAutoDescriptionOnView` functionality, but combined with a description purge on edit.

TextExtract might be depreciated in the future soon if Page Content Service or something similar available in the REST API. Afaik no WMF production sites run them anymore and Popups explicitly recommend to not to use TextExtract, though there's no built alternative available for 3rd parties.

**Comment by octfx** [comment]
Classic WMF 😪
I'll add a todo issue to track when Page Content Service is available
