### ISSUE TITLE
Link to WikiSEO extension contains typo, duplicate https:// prefix

### ISSUE THREAD

**Issue by dmehus** [octfx/wiki-seo#26]
On the "page information" screen of any wiki, the link, `https://https//mediaiwki.org/wiki/Extension:WikiSEO` to the WikiSEO extension contains a duplicate `https://` prefix and also the address should be `www.mediawiki.org` not `mediaiwki.org`. Thanks.

**Comment by octfx** [comment]
Thanks for the report, which locale are you using?

**Comment by RhinosF1** [comment]
Can reproduce in en

**Comment by RhinosF1** [comment]
https://test3.miraheze.org/w/index.php?title=Test101&action=info&uselang=en

**Comment by octfx** [comment]
Should be fixed. Translation in `qqq.json` was adding two `https`.

**Comment by dmehus** [comment]
@octfx Thanks for the fix. :)
