### ISSUE TITLE
$wgMetadataGenerators (and probably more config) is not working

### ISSUE THREAD

**Issue by kam193** [octfx/wiki-seo#27]
Hi,
I recognize that setting `$wgMetadataGenerators` has no result at all in my environments (a working wiki as well as local development). The only way to change metadata generators is to modify `extension.json`.

My configuration in `LocalSettings.php` looks like:
```php
wfLoadExtension( 'WikiSEO' );
$wgMetadataGenerators = ["MyCustomPlugin"];
```
(or any other change)

After some research, I found the https://www.mediawiki.org/wiki/Manual:Configuration_for_developers manual. It recommends a bit different usage of configuration. I tried it:

1) in `extension.json`, I added:
```json
"ConfigRegistry": {
	"WikiSEO": "GlobalVarConfig::newInstance"
},
```
2) In `WikiSEO.php`, on line 182, I replaced existing `getMainConfig` with:
```php
MediaWikiServices::getInstance()->getConfigFactory()->makeConfig('WikiSEO')->get( 'MetadataGenerators' );
```

...and now it works. I'm unsure if there is something wrong with what I do, or something wrong with the usage of `getMainConfig`

**Comment by octfx** [comment]
Thanks for the find!

You are very welcome to create a pull request :)

**Comment by kam193** [comment]
Yeah, but after working longer with my change, I recognize more strange behavior:

Regardless of using `getMainConfig` or config factory, the `$wgMetadataGenerators` value is added to the value from `extension.json`. Due to using existing key in producing HTML output, I thought initially that local config is ignored. 

I'm not getting it, to be honest. It makes no sense to me. I'll create PR if I understand the behavior, and I'd be sure I know what I'm doing ;)

**Comment by octfx** [comment]
So, I think I've found the issue. The default behaviour is to merge both arrays, as all three generators are defined in  `extension.json`, setting `$wgMetadataGenerators = []` results in the following merge:  
`array_merge(["OpenGraph", "..."], [])` -> all three generators are still present.

Commit https://github.com/octfx/wiki-seo/commit/3e62923af886553ed7f7f580c4e3f56bae242a43 changes the default config, so setting `$wgMetadataGenerators = ["MyCustomPlugin"];` should work!

**Comment by octfx** [comment]
Closing this for now
