### ISSUE TITLE
WikiSEO adds extraneous newline (`<br />`)

### ISSUE THREAD

**Issue by adrelanos** [octfx/wiki-seo#30]
Normally in MediaWiki one can write various magic words, templates, widgets, etc. into new lines in the MediaWiki markup without these generating newlines. However, WikiSEO seems to inject extraneous newlines.

Example...

Broken, extraneous newline (`<br />`):

```
{{Header}}
{{#seo:
|description=test
}}
```

OK, no extraneous newline (`<br />`):

```
{{Header}} {{#seo:
|description=test
}}
```

Is there some way to tell the MediaWiki parser "do not add any newline (`<br />`) after invocation of `{{#seo}}`?

**Comment by octfx** [comment]
Thats strange behaviour. On which MW version is this happening?

I don't see as to why an extra `<br />` is added to the page, as the extension itself doesn't add any output other than possible errors. 
On success an empty string is returned: https://github.com/octfx/wiki-seo/blob/d46947908f9f03095c1a9ee5fc4be4c571e54356/includes/WikiSEO.php#L503

The following test:
```
Before
{{#seo:
|title=Test-Title2
|description=Description is functional.
}}
After
```
yields this html on MW 1.35.5:
![msedge_KWgyDpsK41](https://user-images.githubusercontent.com/6594492/149916131-c76b2f2e-cd42-43b7-8c82-c7576fe738f5.png)

**Comment by adrelanos** [comment]
> Thats strange behaviour. On which MW version is this happening?

1.37.1

> `return [ '' ];`

Is that the standard way to do it?

**Comment by octfx** [comment]
So I've installed 1.37.1 and added the same code as above and got the exact same output without any `<br />`.  :/
Can you share the content of the `{{Header}}` template? Maybe that is adding some unwanted newline.

**Comment by adrelanos** [comment]
The content of `{{Header}}` could be for bug report demonstration purposes as simple as:

```
__NOTOC__
```

`__NOTOC__` by itself does not cause an extraneous newline.

**Comment by adrelanos** [comment]
To simplify this bug report, now avoiding a separate template.

Broken, extraneous newline (`<br />`):

```
__NOTOC__
{{#seo:
|description=test
}}
This is the first line of the content text.
```

OK, no extraneous newline (`<br />`):

```
__NOTOC__ {{#seo:
|description=test
}}
This is the first line of the content text.
```

Reproducible?

**Comment by octfx** [comment]
Thank you for this!  
I can indeed reproduce this. Seems like very strange parser behaviour.

I've implemented a local fix which outputs a zeero width space instead of nothing. But I'm waiting on some other developer responses to see if there is a better way.

**Comment by octfx** [comment]
Instead of outputting nothing, the extension now outputs a zero width space. This removes the `<br/>`, patch is live on master.

**Comment by adrelanos** [comment]
Thank you very much for looking into this!

I don't understand the diff / I don't understand commit https://github.com/octfx/wiki-seo/commit/a6980884fb91cf3ff6c6b3fe905cdd79a466e200.

old:

    return [ '​' ];

new:

    return [ '​' ];

old is exactly the same as new. I used the inside browser search and it is exactly the same. So the only thing that commit actually changed is adding the comment on top.

Is the commit wrong or is it some special character that isn't correctly rendered on github or am I missing something?

**Comment by octfx** [comment]
There is an actual character between `''`, a zero width space.  
GitHub doesn't seem to render this, but you could copy `'​'`, paste it into a text editor and step through it using the arrow keys.  
You'll notice that the cursor only moves after hitting the arrow key two times.

**Comment by adrelanos** [comment]
Tester the master branch just now. Actually a regression. In the HTML I am now seeing:

```
<p>&ZeroWidthSpace;  </p>
```

Which causes a newline  (`<br />`).

Or.

```
<pre>&ZeroWidthSpace;
</pre>
```

**Comment by adrelanos** [comment]
Instead of (`&ZeroWidthSpace;`)

    return [ '​' ];

what do you think about using a HTML comment instead?

    return [ '​' ];

I am testing this right now. Seems very promising to me.

**Comment by octfx** [comment]
Totally forgot about HTML comments, thats a greate idea!

**Comment by adrelanos** [comment]
https://github.com/octfx/wiki-seo/pull/31

:)

**Comment by octfx** [comment]
> #31
> 
> :)

I'd love to merge your PR, but [Gerrit](https://gerrit.wikimedia.org/g/mediawiki/extensions/WikiSEO) is used as the main development tool. This is "just" a mirror for easier access to issues. :/

I've pushed your commit and will update this repo in the following minutes

**Comment by adrelanos** [comment]
Thank you!
