### ISSUE TITLE
Add ability to set hreflang attributes

### ISSUE THREAD

**Issue by octfx** [octfx/wiki-seo#5]
Feature description: https://moz.com/learn/seo/hreflang-tag
Reported in: https://www.mediawiki.org/w/index.php?title=Topic:Vcrma2652c9wxlik&topic_showPostId=vdqky5f7dvgxyd81#flow-post-vdqky5f7dvgxyd81

**Comment by Sen-Sai** [comment]
Yes it would be great if we can add following tags to the header :
```
<link rel="alternate" href="<link to dutch version" hreflang="nl-nl">
<link rel="alternate" href="<link to english version>" hreflang="en-us">
```
Where one could be the default url of the page with perhaps an extension setting to define the standard language.
So if en-us is default, the extension will always add :
`<link rel="alternate" href="<url of the page shown>" hreflang="en-us">`
to the header and per page you can tell the extension if you have another version of this page (or perhaps even more) in a different language..

**Comment by octfx** [comment]
Can I assume that the language key in the url is always the same?  
For example:
```
nl-nl = example.com/<article>/nl-nl/
en-us = example.com/<article>/en-us/
...
```

My idea for setting the values is something like:
```
{{#seo:
...
|hreflangs=nl-nl,en-us,...
}}
```
Which would result in the generated urls above.

Or can/should the url be configurable for each language?

**Comment by Sen-Sai** [comment]
Well yes.. the page in a different language could be on another website.
So you can get :
```
<link rel="alternate" href="https://example.de/hallo-welt" hreflang="de-de">
<link rel="alternate" href="https://example.com/hello-world" hreflang="en-us">
```
So even if you are on the German example.de/hallo-welt you still need to have the german hreflang to its own page and any additional ones for the translations.
It could also be something like :
```
<link rel="alternate" href="https://example.com/de/hallo-welt" hreflang="de-de">
<link rel="alternate" href="https://example.com/en/hello-world" hreflang="en-us">
```

**Comment by octfx** [comment]
Got it.
I'm proposing something in the form of:
```
{{#seo:
|hreflang_de-de=https://example.com/de/..., 
|hreflang_nl-nl=https://example.nl/nl/..., 
}}
```
What do you think?

**Comment by Sen-Sai** [comment]
Yes that will do. Although you could also have a localsettings option where you can define the default language (e.g. de-de) and the wikiSEO extension can then always add the default link automatically.
So if you are on the german website 
`<link rel="alternate" href="<current url of the page shown>" hreflang="de-de">`
Will be added automatically. This way if the website has only one language, the webmaster doesn't have to do anything, it will be there automatically. If he does have another language he would only have to add :
```
{{#seo:
|hreflang_nl-nl=<dutchversionUrl>
}}
```

**Comment by octfx** [comment]
So if `$wgSeoDefaultLanguage` is set, the extension would add a `href` link for the current pageurl?

**Comment by Sen-Sai** [comment]
Yeah if `$wgSeoDefaultLanguage` = 'de-de' the extension could add it to the head of the html automatically with the the current url of the page shown:
`<link rel="alternate" href="<current url of the page shown>" hreflang="de-de">`

**Comment by octfx** [comment]
Released in https://github.com/octfx/wiki-seo/commit/9c0ff461006570b9b2824d1967ebc3248df98fd7
